version: "3"
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - node
  node:
    container_name: "node"
    build:
      context: ./dockerFileNodeDemo
      dockerfile: Dockerfile
    ports:
      - "3000:8000"